# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventi'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Squadra', 'verbose_name_plural': 'Squadre'},
        ),
    ]
