# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Punti')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adidas.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.ManyToManyField(through='adidas.PlayerPoints', to='adidas.Event'),
        ),
    ]
