# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:03
from __future__ import unicode_literals

import adidas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0002_auto_20170223_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(null=True, upload_to=adidas.models.user_directory_path),
        ),
    ]
