# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:58
from __future__ import unicode_literals

import adidas.models
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0003_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='allowed_teams',
            field=models.ManyToManyField(to='adidas.Team', verbose_name='Squadre abilitate'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data di fine'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Ora di fine'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=adidas.models.event_directory_path, verbose_name="Immagine del'evento"),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data di inizio'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Ora di inizio'),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=256, null=True, verbose_name='Luogo'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(null=True, upload_to=adidas.models.user_directory_path, verbose_name='Immagine del profili'),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.ManyToManyField(through='adidas.PlayerPoints', to='adidas.Event', verbose_name='Punti'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='adidas.TeamMembership', to=settings.AUTH_USER_MODEL, verbose_name='Membri'),
        ),
    ]
