# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adidas', '0003_createsuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giocatore',
                'verbose_name_plural': 'Giocatori',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='adidas.TeamMembership', to='adidas.Player'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adidas.Player'),
        ),
    ]
