# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0004_auto_20170227_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Numero di telefono non valido.', regex='^\\d{7,13}$')], verbose_name='Numero di telefono'),
        ),
    ]
