# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0005_auto_20170210_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='leader',
        ),
        migrations.AddField(
            model_name='player',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(verbose_name='Ora'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='date_joined',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
    ]
