# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:26
from __future__ import unicode_literals

import adidas.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0005_player_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, validators=[adidas.models.valid_birth_date], verbose_name='Data di nascita'),
        ),
    ]
