# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0006_auto_20170227_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='player',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adidas.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_joined',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='playerpoints',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adidas.Event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='playerpoints',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Giocatore'),
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
