# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:29
from __future__ import unicode_literals

import adidas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0008_auto_20170227_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hash',
            field=models.CharField(default=adidas.models.generate_uid, max_length=50, verbose_name='Codice adesione'),
        ),
    ]
