# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0009_team_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(to='adidas.Team', verbose_name='Squadre iscritte'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allowed_teams',
            field=models.ManyToManyField(related_name='allowed_teams', to='adidas.Team', verbose_name='Squadre abilitate'),
        ),
    ]
