# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0013_auto_20170302_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_leader',
            new_name='is_captain',
        ),
    ]
