# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 16:14
from __future__ import unicode_literals

import adidas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0014_auto_20170303_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hash',
            field=models.CharField(default=adidas.models.generate_uid, max_length=50, verbose_name='Codice adesione'),
        ),
    ]
