# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adidas', '0016_auto_20170303_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('co', 'Coming soon'), ('op', 'Registrazioni aperte'), ('cl', 'Registrazioni chiuse'), ('hi', 'Invisibile')], default='co', max_length=2, verbose_name='Stato'),
        ),
    ]
