# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=19, verbose_name='Provider')),
                ('text', models.TextField(verbose_name='Testo')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('comments', models.IntegerField(default=0, verbose_name='Commenti')),
                ('shares', models.IntegerField(default=0, verbose_name='Condivisioni')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
