# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcrawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(default='', verbose_name='Url Immagine'),
        ),
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.CharField(default=None, max_length=100, verbose_name='UID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='Testo'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('uid', 'provider')]),
        ),
    ]
